//go:build js && wasm

// Copyright 2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package bls12377

import (
	"errors"
	"fmt"
	"math/big"
	"math/bits"
	"sync"

	curve "github.com/consensys/gnark-crypto/ecc/bls12-377"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fp"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr/fft"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr/iop"
	"github.com/consensys/gnark/backend/accelerated/webgpu/internal/bridge"
	native "github.com/consensys/gnark/backend/plonk/bls12-377"
	cs "github.com/consensys/gnark/constraint/bls12-377"
)

const curveKey = "bls12_377"

var client = bridge.Client{GlobalName: "gnarkPlonkWebGPU", ErrorPrefix: "webgpu plonk " + curveKey}

// Layout of the fused numerator kernel inputs (see web/src/curvegpu/bridge.ts).
const (
	numeratorDynamicVectors = 5 // L, R, O, Z, Qk, followed by the BSB22 committed values
	numeratorStaticVectors  = 7 // Ql, Qr, Qm, Qo, S1, S2, S3, followed by the BSB22 selectors
	numeratorScalars        = 7 // per coset: coset, Lagrange scale, cs, cs², β, γ, α
)

// Accelerator implements native.Accelerator by running the MSMs, the quotient
// numerator and the large inverse FFT of the PLONK prover on the browser WebGPU
// runtime.
type Accelerator struct {
	pk     *native.ProvingKey
	mu     sync.Mutex
	handle string
	bases  bridge.BasisRegistry
	cache  *numeratorCache
}

// Attach uploads the SRS of pk to the GPU and attaches a WebGPU accelerator to
// pk. It is idempotent.
func Attach(pk *native.ProvingKey) (*Accelerator, error) {
	if acc, ok := pk.Accelerator().(*Accelerator); ok && acc.pk == pk {
		return acc, nil
	}
	acc := &Accelerator{pk: pk}
	if err := acc.prepare(); err != nil {
		return nil, err
	}
	pk.SetAccelerator(acc)
	return acc, nil
}

func (a *Accelerator) prepare() error {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.handle != "" {
		return nil
	}
	if err := client.Init(curveKey); err != nil {
		return err
	}
	g1 := map[string][]byte{
		"kzg":         bridge.Bytes(a.pk.Kzg.G1),
		"kzgLagrange": bridge.Bytes(a.pk.KzgLagrange.G1),
	}
	bridge.RegisterSlice(&a.bases, "kzg", a.pk.Kzg.G1)
	bridge.RegisterSlice(&a.bases, "kzgLagrange", a.pk.KzgLagrange.G1)
	handle, err := client.PrepareKey(curveKey, g1, nil)
	if err != nil {
		return err
	}
	a.handle = handle
	return nil
}

// Release frees the GPU resources and detaches the accelerator from its proving key.
func (a *Accelerator) Release() error {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.pk.Accelerator() == native.Accelerator(a) {
		a.pk.SetAccelerator(nil)
	}
	a.cache = nil
	if a.handle == "" {
		return nil
	}
	err := client.ReleaseKey(a.handle)
	a.handle = ""
	return err
}

// Prewarm builds the circuit-dependent caches (canonical and coset forms of the
// circuit polynomials, FFT tables, compiled kernels) so that the first proof
// does not pay for them. A proving key is bound to a single circuit, which
// must be spr.
func (a *Accelerator) Prewarm(spr *cs.SparseR1CS) error {
	domain0, domain1 := domains(spr)
	trace := native.NewTrace(spr, domain0)
	statics := staticPolys{
		ql: trace.Ql, qr: trace.Qr, qm: trace.Qm, qo: trace.Qo,
		s1: trace.S1, s2: trace.S2, s3: trace.S3,
		qcp: trace.Qcp,
	}
	cache, err := a.numeratorCache(domain0, domain1, statics)
	if err != nil {
		return err
	}
	if err := a.uploadStatics(cache); err != nil {
		return err
	}
	n := int(domain0.Cardinality)
	if err := client.PrewarmQuotientTransformDomain(curveKey, n); err != nil {
		return err
	}
	if err := client.PrewarmQuotientEvaluateKernel(curveKey, len(trace.Qcp)); err != nil {
		return err
	}
	return client.PrewarmQuotientCanonicalizeDomain(curveKey, int(domain1.Cardinality))
}

// domains mirrors the FFT domain selection of the native prover.
func domains(spr *cs.SparseR1CS) (*fft.Domain, *fft.Domain) {
	sizeSystem := uint64(spr.GetNbConstraints() + len(spr.Public))
	domain0 := fft.NewDomain(sizeSystem)
	if sizeSystem < 6 {
		return domain0, fft.NewDomain(8*sizeSystem, fft.WithoutPrecompute())
	}
	return domain0, fft.NewDomain(4*sizeSystem, fft.WithoutPrecompute())
}

// MultiExp implements native.Accelerator.
func (a *Accelerator) MultiExp(bases []curve.G1Affine, scalars []fr.Element) (curve.G1Affine, error) {
	var res curve.G1Affine
	if len(scalars) > len(bases) {
		return res, errors.New(client.ErrorPrefix + ": more scalars than bases")
	}
	if len(scalars) == 0 {
		return res, nil
	}
	name, start, ok := bridge.ResolveSlice(&a.bases, bases[:len(scalars)])
	if !ok {
		return res, errors.New(client.ErrorPrefix + ": bases are not part of the proving key SRS")
	}
	packed, err := client.MSMG1(a.handle, name, start, scalarsRegularLE(scalars))
	if err != nil {
		return res, err
	}
	return decodeG1(packed)
}

// ToCanonical implements native.Accelerator.
func (a *Accelerator) ToCanonical(domain *fft.Domain, p *iop.Polynomial) error {
	if uint64(len(p.Coefficients())) != domain.Cardinality {
		return fmt.Errorf("%s: polynomial has %d coefficients, expected %d", client.ErrorPrefix, len(p.Coefficients()), domain.Cardinality)
	}
	return canonicalize([]*iop.Polynomial{p})
}

// ComputeNumerator implements native.Accelerator.
func (a *Accelerator) ComputeNumerator(in *native.NumeratorInput) (*iop.Polynomial, error) {
	n := int(in.Domain0.Cardinality)
	rho := int(in.Domain1.Cardinality / in.Domain0.Cardinality)
	statics := staticPolys{
		ql: in.Ql, qr: in.Qr, qm: in.Qm, qo: in.Qo,
		s1: in.S1, s2: in.S2, s3: in.S3,
		qcp: in.Qcp,
	}
	cache, err := a.numeratorCache(in.Domain0, in.Domain1, statics)
	if err != nil {
		return nil, err
	}
	// the prover expects the circuit polynomials in canonical form on return:
	// point them at the cached canonical copies (read-only from here on).
	cache.canonical.applyTo(statics)

	dynamic := append([]*iop.Polynomial{in.L, in.R, in.O, in.Z, in.Qk}, in.Pi...)
	commitmentCount := len(in.Pi)
	vectorBytes := n * fr.Bytes
	dynamicPacked := make([]byte, len(dynamic)*vectorBytes)
	for i, p := range dynamic {
		if p == nil || len(p.Coefficients()) != n {
			return nil, fmt.Errorf("%s: numerator input %d is missing or has the wrong size", client.ErrorPrefix, i)
		}
		packRegularLE(dynamicPacked[i*vectorBytes:(i+1)*vectorBytes], p.Coefficients())
	}

	// blinding polynomials, scaled per coset: bl(X) · ((s·ωⁱ)ⁿ − 1) with the
	// power of the coset shifter folded into the coefficients.
	blinds := [][]fr.Element{in.Bl.Coefficients(), in.Br.Coefficients(), in.Bo.Coefficients(), in.Bz.Coefficients()}
	blindCoeffCount := 0
	for _, b := range blinds {
		blindCoeffCount = max(blindCoeffCount, len(b))
	}
	blindBytes := len(blinds) * blindCoeffCount * fr.Bytes
	blindsPacked := make([]byte, rho*blindBytes)
	scalarsPacked := make([]byte, rho*numeratorScalars*fr.Bytes)
	aux := &cache.aux
	for i := 0; i < rho; i++ {
		for j, b := range blinds {
			start := i*blindBytes + j*blindCoeffCount*fr.Bytes
			acc := aux.cosetExpMinusOnes[i]
			for k := range b {
				var scaled fr.Element
				scaled.Mul(&b[k], &acc)
				fr.LittleEndian.PutElement((*[fr.Bytes]byte)(blindsPacked[start+k*fr.Bytes:start+(k+1)*fr.Bytes]), scaled)
				acc.Mul(&acc, &aux.cosets[i])
			}
		}
		packRegularLE(scalarsPacked[i*numeratorScalars*fr.Bytes:(i+1)*numeratorScalars*fr.Bytes], []fr.Element{
			aux.cosets[i], aux.lagrangeScales[i], aux.cs, aux.css, in.Beta, in.Gamma, in.Alpha,
		})
	}

	a.mu.Lock()
	uploaded := cache.uploaded
	a.mu.Unlock()
	var staticPacked, twiddles, scaling, denominators []byte
	if !uploaded {
		staticPacked = cache.packCosets()
		twiddles, scaling, denominators = aux.twiddlesPacked, aux.scalingPacked, aux.denominatorsPacked
	}
	out, err := client.TransformAndEvaluateQuotientCosets(curveKey,
		dynamicPacked, scaling, staticPacked, cache.staticKeysPacked(), twiddles, denominators, blindsPacked, scalarsPacked,
		n, blindCoeffCount, commitmentCount, int(nextCacheKey()), rho, int(cache.auxKey))
	if err != nil {
		return nil, err
	}
	if len(out) != rho*vectorBytes {
		return nil, fmt.Errorf("%s: numerator kernel returned %d bytes, expected %d", client.ErrorPrefix, len(out), rho*vectorBytes)
	}
	a.mu.Lock()
	cache.uploaded = true
	a.mu.Unlock()

	// the result is built in bit reverse order on the large domain
	cres := make([]fr.Element, in.Domain1.Cardinality)
	buf := make([]fr.Element, n)
	mm := uint64(64 - bits.TrailingZeros64(in.Domain1.Cardinality))
	for i := 0; i < rho; i++ {
		if err := unpackRegularLE(buf, out[i*vectorBytes:(i+1)*vectorBytes]); err != nil {
			return nil, err
		}
		for j := 0; j < n; j++ {
			cres[bits.Reverse64(uint64(rho*j+i))>>mm] = buf[j]
		}
	}

	// the prover opens L, R, O, Z and the committed values later: back to canonical form
	if err := canonicalize(append([]*iop.Polynomial{in.L, in.R, in.O, in.Z}, in.Pi...)); err != nil {
		return nil, err
	}
	return iop.NewPolynomial(&cres, iop.Form{Basis: iop.LagrangeCoset, Layout: iop.BitReverse}), nil
}

// staticPolys are the circuit polynomials of the trace.
type staticPolys struct {
	ql, qr, qm, qo, s1, s2, s3 *iop.Polynomial
	qcp                        []*iop.Polynomial
}

func (p staticPolys) all() []*iop.Polynomial {
	return append([]*iop.Polynomial{p.ql, p.qr, p.qm, p.qo, p.s1, p.s2, p.s3}, p.qcp...)
}

func (p staticPolys) clone() staticPolys {
	res := staticPolys{
		ql: p.ql.Clone(), qr: p.qr.Clone(), qm: p.qm.Clone(), qo: p.qo.Clone(),
		s1: p.s1.Clone(), s2: p.s2.Clone(), s3: p.s3.Clone(),
		qcp: make([]*iop.Polynomial, len(p.qcp)),
	}
	for i := range p.qcp {
		res.qcp[i] = p.qcp[i].Clone()
	}
	return res
}

// applyTo makes the polynomials of dst share the coefficients of p.
func (p staticPolys) applyTo(dst staticPolys) {
	*dst.ql, *dst.qr, *dst.qm, *dst.qo = *p.ql, *p.qr, *p.qm, *p.qo
	*dst.s1, *dst.s2, *dst.s3 = *p.s1, *p.s2, *p.s3
	for i := range p.qcp {
		*dst.qcp[i] = *p.qcp[i]
	}
}

// numeratorCache holds, for one circuit, the circuit polynomials in canonical
// form and evaluated on each of the ρ cosets, plus the per-coset tables the
// kernel needs. The static vectors are uploaded to the GPU once and referenced
// by cache keys afterwards.
type numeratorCache struct {
	n, rho, qcpCount int
	canonical        staticPolys
	cosets           []staticPolys
	aux              numeratorAux
	staticKeys       []uint32
	auxKey           uint32
	uploaded         bool
}

type numeratorAux struct {
	twiddlesPacked, scalingPacked, denominatorsPacked []byte
	cosets, cosetExpMinusOnes, lagrangeScales         []fr.Element
	cs, css                                           fr.Element
}

var (
	cacheKeyMu   sync.Mutex
	cacheKeyNext uint32
)

// nextCacheKey returns a process-wide unique, non-zero key for the runtime's caches.
func nextCacheKey() uint32 {
	cacheKeyMu.Lock()
	defer cacheKeyMu.Unlock()
	cacheKeyNext++
	if cacheKeyNext == 0 {
		cacheKeyNext = 1
	}
	return cacheKeyNext
}

func (a *Accelerator) numeratorCache(domain0, domain1 *fft.Domain, statics staticPolys) (*numeratorCache, error) {
	a.mu.Lock()
	defer a.mu.Unlock()
	n := int(domain0.Cardinality)
	rho := int(domain1.Cardinality / domain0.Cardinality)
	if c := a.cache; c != nil && c.n == n && c.rho == rho && c.qcpCount == len(statics.qcp) {
		return c, nil
	}

	canonical := statics.clone()
	if err := canonicalize(canonical.all()); err != nil {
		return nil, err
	}
	cosetTable, err := domain0.CosetTable()
	if err != nil {
		return nil, err
	}
	scaling := cosetTable
	working := canonical.clone()
	cosets := make([]staticPolys, rho)
	for i := 0; i < rho; i++ {
		if i == 1 {
			// from the second coset on, shift by the generator of the large domain
			scaling = make([]fr.Element, n)
			fft.BuildExpTable(domain1.Generator, scaling)
		}
		if err := toCoset(working.all(), scaling); err != nil {
			return nil, err
		}
		cosets[i] = working.clone()
	}
	aux, err := buildNumeratorAux(domain0, domain1)
	if err != nil {
		return nil, err
	}
	c := &numeratorCache{
		n: n, rho: rho, qcpCount: len(statics.qcp),
		canonical: canonical, cosets: cosets, aux: aux,
		staticKeys: make([]uint32, rho), auxKey: nextCacheKey(),
	}
	for i := range c.staticKeys {
		c.staticKeys[i] = nextCacheKey()
	}
	a.cache = c
	return c, nil
}

// uploadStatics sends the static kernel inputs to the runtime ahead of the first proof.
func (a *Accelerator) uploadStatics(c *numeratorCache) error {
	a.mu.Lock()
	uploaded := c.uploaded
	a.mu.Unlock()
	if uploaded {
		return nil
	}
	if err := client.PreloadQuotientStaticAndAux(curveKey,
		c.packCosets(), c.staticKeysPacked(), c.aux.scalingPacked, c.aux.twiddlesPacked, c.aux.denominatorsPacked,
		c.n, numeratorStaticVectors+c.qcpCount, c.rho, int(c.auxKey)); err != nil {
		return err
	}
	a.mu.Lock()
	c.uploaded = true
	a.mu.Unlock()
	return nil
}

func (c *numeratorCache) staticKeysPacked() []byte {
	out := make([]byte, 4*len(c.staticKeys))
	for i, k := range c.staticKeys {
		out[4*i], out[4*i+1], out[4*i+2], out[4*i+3] = byte(k), byte(k>>8), byte(k>>16), byte(k>>24)
	}
	return out
}

// packCosets packs, coset after coset, the static vectors in regular little-endian form.
func (c *numeratorCache) packCosets() []byte {
	vectorBytes := c.n * fr.Bytes
	perCoset := (numeratorStaticVectors + c.qcpCount) * vectorBytes
	out := make([]byte, c.rho*perCoset)
	for i, coset := range c.cosets {
		for j, p := range coset.all() {
			start := i*perCoset + j*vectorBytes
			packRegularLE(out[start:start+vectorBytes], p.Coefficients())
		}
	}
	return out
}

// buildNumeratorAux computes the per-coset tables of the CPU prover's
// computeNumerator: twiddles of the small domain, coset scaling vectors, the
// inverses of (s·ωⁱ − 1) used by L₁, and the per-coset scalars.
func buildNumeratorAux(domain0, domain1 *fft.Domain) (numeratorAux, error) {
	n := int(domain0.Cardinality)
	rho := int(domain1.Cardinality / domain0.Cardinality)
	twiddles0 := make([]fr.Element, n)
	if n == 1 {
		twiddles0[0].SetOne()
	} else {
		twiddles, err := domain0.Twiddles()
		if err != nil {
			return numeratorAux{}, err
		}
		copy(twiddles0, twiddles[0])
		w := twiddles0[1]
		for i := len(twiddles[0]); i < n; i++ {
			twiddles0[i].Mul(&twiddles0[i-1], &w)
		}
	}
	cosetTable, err := domain0.CosetTable()
	if err != nil {
		return numeratorAux{}, err
	}
	vectorBytes := n * fr.Bytes
	aux := numeratorAux{
		twiddlesPacked:     make([]byte, vectorBytes),
		scalingPacked:      make([]byte, rho*vectorBytes),
		denominatorsPacked: make([]byte, rho*vectorBytes),
		cosets:             make([]fr.Element, rho),
		cosetExpMinusOnes:  make([]fr.Element, rho),
		lagrangeScales:     make([]fr.Element, rho),
	}
	packRegularLE(aux.twiddlesPacked, twiddles0)
	aux.cs.Set(&domain1.FrMultiplicativeGen)
	aux.css.Square(&aux.cs)

	denominators := make([]fr.Element, n)
	buf := make([]fr.Element, n)
	scaling := make([]fr.Element, n)
	var coset, one fr.Element
	coset.SetOne()
	one.SetOne()
	bn := big.NewInt(int64(n))
	for i := 0; i < rho; i++ {
		if i == 0 {
			coset.Mul(&coset, &domain1.FrMultiplicativeGen)
		} else {
			coset.Mul(&coset, &domain1.Generator)
		}
		aux.cosets[i] = coset
		aux.cosetExpMinusOnes[i].Exp(coset, bn).Sub(&aux.cosetExpMinusOnes[i], &one)
		aux.lagrangeScales[i].Mul(&aux.cosetExpMinusOnes[i], &domain0.CardinalityInv)
		for j := 0; j < n; j++ {
			denominators[j].Mul(&coset, &twiddles0[j]).Sub(&denominators[j], &one)
		}
		batchInvert(denominators, buf)
		packRegularLE(aux.denominatorsPacked[i*vectorBytes:(i+1)*vectorBytes], denominators)
		if i == 0 {
			packRegularLE(aux.scalingPacked[:vectorBytes], cosetTable)
		} else {
			fft.BuildExpTable(coset, scaling)
			packRegularLE(aux.scalingPacked[i*vectorBytes:(i+1)*vectorBytes], scaling)
		}
	}
	return aux, nil
}

// batchInvert inverts vec in place with the Montgomery trick, using buf as scratch.
func batchInvert(vec, buf []fr.Element) {
	copy(buf, vec)
	for i := 1; i < len(vec); i++ {
		vec[i].Mul(&vec[i], &vec[i-1])
	}
	acc := vec[len(vec)-1]
	acc.Inverse(&acc)
	for i := len(vec) - 1; i > 0; i-- {
		vec[i].Mul(&acc, &vec[i-1])
		acc.Mul(&acc, &buf[i])
	}
	vec[0].Set(&acc)
}

// toCoset moves canonical polynomials to the Lagrange basis of the coset
// described by scaling (evaluation at scaling[j]·ωʲ).
func toCoset(polys []*iop.Polynomial, scaling []fr.Element) error {
	if err := canonicalize(polys); err != nil {
		return err
	}
	for _, p := range polys {
		c := p.Coefficients()
		for j := range c {
			c[j].Mul(&c[j], &scaling[j])
		}
	}
	return toLagrange(polys)
}

type canonicalizeKey struct{ bitReversed, coset bool }

// canonicalize converts polys in place to canonical basis, Regular layout,
// batching the GPU inverse FFTs by input form. nil entries are skipped.
func canonicalize(polys []*iop.Polynomial) error {
	groups := map[canonicalizeKey][]*iop.Polynomial{}
	n := -1
	for _, p := range polys {
		if p == nil {
			continue
		}
		if p.Basis == iop.Canonical {
			p.ToRegular()
			continue
		}
		if n < 0 {
			n = len(p.Coefficients())
		} else if len(p.Coefficients()) != n {
			return errors.New(client.ErrorPrefix + ": canonicalize: polynomials of different sizes")
		}
		if p.Basis != iop.Lagrange && p.Basis != iop.LagrangeCoset {
			return fmt.Errorf("%s: unsupported polynomial basis %d", client.ErrorPrefix, p.Basis)
		}
		if p.Layout != iop.Regular && p.Layout != iop.BitReverse {
			return fmt.Errorf("%s: unsupported polynomial layout %d", client.ErrorPrefix, p.Layout)
		}
		k := canonicalizeKey{bitReversed: p.Layout == iop.BitReverse, coset: p.Basis == iop.LagrangeCoset}
		groups[k] = append(groups[k], p)
	}
	for k, group := range groups {
		if err := transform(group, n, func(packed []byte) ([]byte, error) {
			return client.CanonicalizeQuotientVectors(curveKey, packed, len(group), n, k.bitReversed, k.coset)
		}, iop.Form{Basis: iop.Canonical, Layout: iop.Regular}); err != nil {
			return err
		}
	}
	return nil
}

// toLagrange converts canonical Regular polynomials in place to Lagrange basis.
func toLagrange(polys []*iop.Polynomial) error {
	var group []*iop.Polynomial
	n := -1
	for _, p := range polys {
		if p == nil {
			continue
		}
		if p.Basis == iop.Lagrange {
			p.ToRegular()
			continue
		}
		if p.Basis != iop.Canonical || p.Layout != iop.Regular {
			return fmt.Errorf("%s: expected canonical regular polynomial, got basis %d layout %d", client.ErrorPrefix, p.Basis, p.Layout)
		}
		if n < 0 {
			n = len(p.Coefficients())
		} else if len(p.Coefficients()) != n {
			return errors.New(client.ErrorPrefix + ": toLagrange: polynomials of different sizes")
		}
		group = append(group, p)
	}
	if len(group) == 0 {
		return nil
	}
	return transform(group, n, func(packed []byte) ([]byte, error) {
		return client.LagrangeQuotientVectors(curveKey, packed, len(group), n)
	}, iop.Form{Basis: iop.Lagrange, Layout: iop.Regular})
}

// transform packs the coefficients of group, runs fn on the GPU and unpacks the
// result back in place, setting the polynomials' form to out.
func transform(group []*iop.Polynomial, n int, fn func([]byte) ([]byte, error), out iop.Form) error {
	vectorBytes := n * fr.Bytes
	packed := make([]byte, len(group)*vectorBytes)
	for i, p := range group {
		packRegularLE(packed[i*vectorBytes:(i+1)*vectorBytes], p.Coefficients())
	}
	res, err := fn(packed)
	if err != nil {
		return err
	}
	if len(res) != len(packed) {
		return fmt.Errorf("%s: transform returned %d bytes, expected %d", client.ErrorPrefix, len(res), len(packed))
	}
	for i, p := range group {
		if err := unpackRegularLE(p.Coefficients(), res[i*vectorBytes:(i+1)*vectorBytes]); err != nil {
			return err
		}
		p.Basis, p.Layout = out.Basis, out.Layout
	}
	return nil
}

// packRegularLE writes values in regular (non Montgomery) little-endian form.
func packRegularLE(dst []byte, values []fr.Element) {
	for i := range values {
		fr.LittleEndian.PutElement((*[fr.Bytes]byte)(dst[i*fr.Bytes:(i+1)*fr.Bytes]), values[i])
	}
}

// unpackRegularLE reads regular little-endian elements, rejecting non reduced values.
func unpackRegularLE(dst []fr.Element, src []byte) error {
	if len(src) != len(dst)*fr.Bytes {
		return fmt.Errorf("%s: expected %d bytes, got %d", client.ErrorPrefix, len(dst)*fr.Bytes, len(src))
	}
	for i := range dst {
		var err error
		if dst[i], err = fr.LittleEndian.Element((*[fr.Bytes]byte)(src[i*fr.Bytes : (i+1)*fr.Bytes])); err != nil {
			return fmt.Errorf("%s: %w", client.ErrorPrefix, err)
		}
	}
	return nil
}

func scalarsRegularLE(scalars []fr.Element) []byte {
	out := make([]byte, len(scalars)*fr.Bytes)
	packRegularLE(out, scalars)
	return out
}

var fpModulusLimbs = func() (m [fp.Limbs]uint64) {
	words := new(big.Int).Set(fp.Modulus()).Bits()
	for i := range words {
		m[i] = uint64(words[i])
	}
	return
}()

// decodeFp reads a Montgomery-form little-endian base field element and checks
// that it is reduced.
func decodeFp(z *fp.Element, b []byte) error {
	copy(bridge.Bytes(z[:]), b)
	for i := fp.Limbs - 1; i >= 0; i-- {
		if z[i] < fpModulusLimbs[i] {
			return nil
		}
		if z[i] > fpModulusLimbs[i] {
			break
		}
	}
	return errors.New(client.ErrorPrefix + ": GPU returned a non reduced field element")
}

func decodeG1(b []byte) (curve.G1Affine, error) {
	var p curve.G1Affine
	if len(b) != 2*fp.Bytes {
		return p, fmt.Errorf("%s: expected %d G1 bytes, got %d", client.ErrorPrefix, 2*fp.Bytes, len(b))
	}
	if err := decodeFp(&p.X, b[:fp.Bytes]); err != nil {
		return p, err
	}
	if err := decodeFp(&p.Y, b[fp.Bytes:]); err != nil {
		return p, err
	}
	if !p.IsInfinity() && !p.IsOnCurve() {
		return p, errors.New(client.ErrorPrefix + ": GPU returned a G1 point that is not on the curve")
	}
	return p, nil
}
