// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package gkr

import (
	"errors"
	"fmt"
	"hash"
	"iter"
	"sync"

	"github.com/consensys/gnark-crypto/utils"
	"github.com/consensys/gnark/constraint"
	"github.com/consensys/gnark/internal/gkr/gkrcore"
	"github.com/consensys/gnark/internal/small_rational"
	"github.com/consensys/gnark/internal/small_rational/polynomial"
)

// Type aliases for bytecode-based GKR types
type (
	Wire    = gkrcore.SerializableWire
	Circuit = gkrcore.SerializableCircuit
)

// The goal is to prove/verify evaluations of many instances of the same circuit

// WireAssignment is the assignment of values to the same wire across many instances of the circuit
type WireAssignment []polynomial.MultiLin

type Proof []sumcheckProof // for each layer, for each wire, a sumcheck (for each variable, a polynomial)

// EvaluationClaim is an assertion that a wire's multilinear extension evaluates to Evaluation at
// EvaluationPoint.
type EvaluationClaim = gkrcore.EvaluationClaim[small_rational.SmallRational]

// Claims are the evaluation claims on circuit inputs and outputs that Prove and Verify return, by
// wire. The consumption order within a wire's slice is up to the caller.
type Claims map[int][]EvaluationClaim

// Check asserts that every claim in c holds against assignment.
func (c Claims) Check(assignment WireAssignment) error {
	for wI, wireClaims := range c {
		for _, claim := range wireClaims {
			eval := assignment[wI].Evaluate(claim.EvaluationPoint, nil)
			if !eval.Equal(&claim.Evaluation) {
				return fmt.Errorf("wire %d: claimed evaluation %v, computed %v", wI, &claim.Evaluation, &eval)
			}
		}
	}
	return nil
}

type resources struct {
	// outgoingEvalPoints[i][k] is the k-th outgoing evaluation point (evaluation challenge) produced at schedule level i.
	// outgoingEvalPoints[len(schedule)][0] holds the initial challenge (firstChallenge / rho).
	// SumcheckLevels produce one point (k=0). SkipLevels pass on all their evaluation points.
	outgoingEvalPoints [][][]small_rational.SmallRational
	nbVars             int
	assignment         WireAssignment
	memPool            polynomial.Pool
	workers            *utils.WorkerPool
	circuit            Circuit
	schedule           constraint.GkrProvingSchedule
	transcript         transcript
	claimValueIndices  [][]int // claimValueIndices[wI][claimI]: index of w's claimI-th claimed value in its source level's finalEvalProof
	claims             Claims
	consolidated       []bool // the wires of schedule[0], indexed by wire
}

// identityGate is the identity gate LevelCircuit and ConsolidationView use to build level 0's
// view of the circuit.
func identityGate() gkrcore.SerializableGate {
	return gkrcore.SerializableGate{Evaluate: gkrcore.IdentityBytecode(), NbIn: 1, Degree: 1}
}

// newResources builds the resources shared by Prove and Verify. It takes no assignment and
// creates no pools; Prove sets those up separately afterward, since Verify needs neither.
func newResources(c Circuit, schedule constraint.GkrProvingSchedule, nbVars int, hasher hash.Hash) resources {
	return resources{
		outgoingEvalPoints: make([][][]small_rational.SmallRational, len(schedule)+1),
		nbVars:             nbVars,
		circuit:            c,
		schedule:           schedule,
		transcript:         transcript{h: hasher},
		claimValueIndices:  c.ClaimValueIndices(schedule),
		claims:             make(Claims),
		consolidated:       c.LevelWires(schedule[0]),
	}
}

// proveSkipLevel evaluates each unique gate input at each inherited evaluation point and records
// the outgoing evaluation points on the resources.
func (r *resources) proveSkipLevel(levelI int) sumcheckProof {
	level := r.schedule[levelI].(*constraint.GkrSkipLevel)
	outPoints := gkrcore.CollectOutgoingEvalPoints(level, levelI, r.outgoingEvalPoints)

	uniqueInputs := r.circuit.UniqueGateInputs(level)
	evals := make([]small_rational.SmallRational, len(uniqueInputs)*len(outPoints))
	for uiI, inW := range uniqueInputs {
		for k, point := range outPoints {
			evals[level.FinalEvalProofIndex(uiI, k)] = r.assignment[inW].Evaluate(point, &r.memPool)
		}
	}
	return sumcheckProof{finalEvalProof: evals}
}

// verifySkipLevel verifies a SkipSumcheck level: checks that the finalEvalProof is consistent with
// the gate evaluations, and records outgoing eval points.
func (r *resources) verifySkipLevel(levelI int, proof Proof) error {
	level := r.schedule[levelI].(*constraint.GkrSkipLevel)
	gkrcore.CollectOutgoingEvalPoints(level, levelI, r.outgoingEvalPoints)

	finalEval := proof[levelI].finalEvalProof
	_, inputIndices := r.circuit.InputMapping(level)
	group := constraint.GkrClaimGroup(*level)

	for levelWireI, wI := range group.Wires {
		wire := r.circuit[wI]
		evaluator := newGateEvaluator(wire.Gate.Evaluate, len(wire.Inputs))
		for claimI, src := range group.ClaimSources {
			for _, inI := range inputIndices[levelWireI] {
				evaluator.pushInput(finalEval[level.FinalEvalProofIndex(inI, claimI)])
			}
			gateEval := evaluator.evaluate()
			claimedEval := proof[src.Level].finalEvalProof[r.claimValueIndices[wI][claimI]]
			if !claimedEval.Equal(gateEval) {
				return fmt.Errorf("level %d wire %d claim %d: claimed eval %v disagrees with gate eval %v", levelI, wI, claimI, &claimedEval, gateEval)
			}
		}
	}
	return nil
}

// levelPredicates returns the bind and include predicates for level levelI's unique gate inputs.
// Level 0 binds nothing and returns every one of its wires (self-referencing on the consolidation
// view); every other level binds every unique gate input that is not an unconsolidated circuit
// input, and returns claims for exactly those it withholds from binding.
func (r *resources) levelPredicates(levelI int) (bind, include func(wI int) bool) {
	if levelI == 0 {
		return func(int) bool { return false }, func(int) bool { return true }
	}
	return func(wI int) bool { return !r.circuit.IsInput(wI) || r.consolidated[wI] },
		func(wI int) bool { return r.circuit.IsInput(wI) && !r.consolidated[wI] }
}

// proveLevel proves level levelI: computes its proof entry, binds its values, and appends its claims.
func (r *resources) proveLevel(levelI int) sumcheckProof {
	var entry sumcheckProof
	switch r.schedule[levelI].(type) {
	case *constraint.GkrSkipLevel:
		entry = r.proveSkipLevel(levelI)
	case *constraint.GkrSingleSourceZeroCheckLevel:
		entry = r.proveSingleSourceZeroCheckLevel(levelI)
	case *constraint.GkrSumcheckLevel:
		entry = r.proveSumcheckLevel(levelI)
	default:
		panic(fmt.Sprintf("level %d: unknown proving level type %T", levelI, r.schedule[levelI]))
	}
	bind, include := r.levelPredicates(levelI)
	constraint.BindGkrFinalEvalProof(&r.transcript, entry.finalEvalProof, r.circuit.UniqueGateInputs(r.schedule[levelI]), bind, r.schedule[levelI])
	gkrcore.AppendLevelClaims(r.claims, r.circuit, r.schedule[levelI], entry.finalEvalProof, r.outgoingEvalPoints[levelI], include)
	return entry
}

// Prove consistency of the claimed assignment. It returns the evaluation claims on the circuit's
// inputs and outputs; the caller must check them. The claim values returned to the caller, the
// output evaluations among them, are not bound into the transcript.
func Prove(c Circuit, schedule constraint.GkrProvingSchedule, assignment WireAssignment, hasher hash.Hash) (Proof, Claims, error) {
	nbInstances := assignment.NumInstances()
	nbVars := assignment.NumVars()
	if 1<<nbVars != nbInstances {
		return nil, nil, errors.New("number of instances must be power of 2")
	}

	r := newResources(c, schedule, nbVars, hasher)
	r.assignment = assignment
	r.memPool = polynomial.NewPool(gkrcore.MemoryRequirements(c, nbInstances)...)
	r.workers = utils.NewWorkerPool()
	defer r.workers.Stop()

	proof := make(Proof, len(schedule)+1)

	// Derive the initial challenge point
	firstChallenge := make([]small_rational.SmallRational, r.nbVars)
	for j := range r.nbVars {
		firstChallenge[j] = r.transcript.getChallenge()
	}
	r.outgoingEvalPoints[len(schedule)] = [][]small_rational.SmallRational{firstChallenge}

	outputs := c.Outputs()
	outputEvals := make([]small_rational.SmallRational, len(outputs))
	for i, w := range outputs {
		outputEvals[i] = r.assignment[w].Evaluate(firstChallenge, &r.memPool)
	}
	proof[len(schedule)] = sumcheckProof{finalEvalProof: outputEvals}
	var boundOutputEvals []small_rational.SmallRational
	for i, w := range outputs {
		if r.consolidated[w] {
			boundOutputEvals = append(boundOutputEvals, outputEvals[i])
		}
	}
	r.transcript.Bind(boundOutputEvals...)
	gkrcore.AppendOutputClaims(r.claims, c, firstChallenge, outputEvals, func(wI int) bool { return !r.consolidated[wI] })

	for levelI := len(schedule) - 1; levelI >= 1; levelI-- {
		proof[levelI] = r.proveLevel(levelI)
	}
	r.circuit = r.circuit.LevelCircuit(r.schedule, 0, identityGate())
	proof[0] = r.proveLevel(0)

	return proof, r.claims, nil
}

// verifyLevel verifies level levelI: checks its proof entry, binds its values, and appends its claims.
func (r *resources) verifyLevel(levelI int, proof Proof) error {
	var err error
	switch r.schedule[levelI].(type) {
	case *constraint.GkrSkipLevel:
		err = r.verifySkipLevel(levelI, proof)
	case *constraint.GkrSingleSourceZeroCheckLevel:
		err = r.verifySingleSourceZeroCheckLevel(levelI, proof)
	case *constraint.GkrSumcheckLevel:
		err = r.verifySumcheckLevel(levelI, proof)
	default:
		panic(fmt.Sprintf("level %d: unknown proving level type %T", levelI, r.schedule[levelI]))
	}
	if err != nil {
		return fmt.Errorf("level %d: %v", levelI, err)
	}
	bind, include := r.levelPredicates(levelI)
	constraint.BindGkrFinalEvalProof(&r.transcript, proof[levelI].finalEvalProof, r.circuit.UniqueGateInputs(r.schedule[levelI]), bind, r.schedule[levelI])
	gkrcore.AppendLevelClaims(r.claims, r.circuit, r.schedule[levelI], proof[levelI].finalEvalProof, r.outgoingEvalPoints[levelI], include)
	return nil
}

// Verify the consistency of the claimed output with the claimed input, and return the evaluation
// claims on the circuit's inputs and outputs. A nil error means nothing until the returned Claims
// are checked: Verify reads no assignment, so the caller must call Claims.Check itself. The claim
// values returned to the caller, the output evaluations among them, are not bound into the
// transcript.
func Verify(c Circuit, schedule constraint.GkrProvingSchedule, logNbInstances int, proof Proof, hasher hash.Hash) (Claims, error) {
	r := newResources(c, schedule, logNbInstances, hasher)

	if len(proof) != len(schedule)+1 {
		return nil, fmt.Errorf("proof has %d levels, expected %d", len(proof), len(schedule)+1)
	}
	outputLevel := proof[len(schedule)]
	if len(outputLevel.partialSumPolys) != 0 {
		return nil, errors.New("output level has partial sum polynomials")
	}
	if len(outputLevel.finalEvalProof) != len(c.Outputs()) {
		return nil, fmt.Errorf("output level has %d evaluations, expected %d", len(outputLevel.finalEvalProof), len(c.Outputs()))
	}

	view := c.LevelCircuit(schedule, 0, identityGate())
	for levelI, level := range schedule {
		levelCircuit := c
		if levelI == 0 {
			levelCircuit = view
		}
		nbUniqueInputs := len(levelCircuit.UniqueGateInputs(level))
		wantFinalEvalLen := nbUniqueInputs * level.NbOutgoingEvalPoints()
		if len(proof[levelI].finalEvalProof) != wantFinalEvalLen {
			return nil, fmt.Errorf("level %d: got %d final evaluations, expected %d", levelI, len(proof[levelI].finalEvalProof), wantFinalEvalLen)
		}
		if _, isSkip := level.(*constraint.GkrSkipLevel); isSkip {
			if len(proof[levelI].partialSumPolys) != 0 {
				return nil, fmt.Errorf("level %d: skip level has partial sum polynomials", levelI)
			}
		} else if len(proof[levelI].partialSumPolys) != logNbInstances {
			return nil, fmt.Errorf("level %d: got %d partial sum polynomials, expected %d", levelI, len(proof[levelI].partialSumPolys), logNbInstances)
		}
	}

	// Derive the initial challenge point
	firstChallenge := make([]small_rational.SmallRational, r.nbVars)
	for j := range r.nbVars {
		firstChallenge[j] = r.transcript.getChallenge()
	}
	r.outgoingEvalPoints[len(schedule)] = [][]small_rational.SmallRational{firstChallenge}
	var boundOutputEvals []small_rational.SmallRational
	for i, w := range c.Outputs() {
		if r.consolidated[w] {
			boundOutputEvals = append(boundOutputEvals, outputLevel.finalEvalProof[i])
		}
	}
	r.transcript.Bind(boundOutputEvals...)
	gkrcore.AppendOutputClaims(r.claims, c, firstChallenge, outputLevel.finalEvalProof, func(wI int) bool { return !r.consolidated[wI] })

	for levelI := len(schedule) - 1; levelI >= 1; levelI-- {
		if err := r.verifyLevel(levelI, proof); err != nil {
			return nil, err
		}
	}
	r.circuit = view
	if err := r.verifyLevel(0, proof); err != nil {
		return nil, err
	}
	return r.claims, nil
}

// Complete the circuit evaluation from input values
func (a WireAssignment) Complete(circuit Circuit) WireAssignment {

	nbInstances := a.NumInstances()
	evaluators := make([]gateEvaluator, len(circuit))

	for i := range circuit {
		if len(a[i]) != nbInstances {
			a[i] = make([]small_rational.SmallRational, nbInstances)
		}
		if !circuit[i].IsInput() {
			evaluators[i] = newGateEvaluator(circuit[i].Gate.Evaluate, len(circuit[i].Inputs))
		}
	}

	for i := range nbInstances {
		for wI := range circuit {
			if !circuit[wI].IsInput() {
				for _, in := range circuit[wI].Inputs {
					evaluators[wI].pushInput(a[in][i])
				}
				a[wI][i].Set(evaluators[wI].evaluate())
			}
		}
	}

	return a
}

func (a WireAssignment) NumInstances() int {
	for _, aW := range a {
		if aW != nil {
			return len(aW)
		}
	}
	panic("empty assignment")
}

func (a WireAssignment) NumVars() int {
	for _, aW := range a {
		if aW != nil {
			return aW.NumVars()
		}
	}
	panic("empty assignment")
}

func iterateElems(elems []small_rational.SmallRational, counter *int, yield func(int, *small_rational.SmallRational) bool) bool {
	for i := range elems {
		if !yield(*counter, &elems[i]) {
			return false
		}
		*counter++
	}
	return true
}

func (p Proof) flatten() iter.Seq2[int, *small_rational.SmallRational] {
	return func(yield func(int, *small_rational.SmallRational) bool) {
		var counter int
		for i := range p {
			for _, poly := range p[i].partialSumPolys {
				if !iterateElems(poly, &counter, yield) {
					return
				}
			}
			if !iterateElems(p[i].finalEvalProof, &counter, yield) {
				return
			}
		}
	}
}

// gateEvaluator provides a high-level API for evaluating compiled gates efficiently.
// It manages the stack internally and handles input buffering, making it easy to
// evaluate the same gate multiple times with different inputs.
type gateEvaluator struct {
	gate gkrcore.GateBytecode
	vars []small_rational.SmallRational
	nbIn int // number of inputs expected
}

// newGateEvaluator creates an evaluator for the given compiled gate.
// The stack is preloaded with constants and ready for evaluation.
func newGateEvaluator(gate gkrcore.GateBytecode, nbIn int, elementPool ...*polynomial.Pool) gateEvaluator {
	e := gateEvaluator{
		gate: gate,
		nbIn: nbIn,
	}
	if len(elementPool) > 0 {
		e.vars = elementPool[0].Make(gate.EvaluatorSize(nbIn))
	} else {
		e.vars = make([]small_rational.SmallRational, gate.EvaluatorSize(nbIn))
	}
	e.vars = e.vars[:gate.NbConstants()]
	for i, constVal := range gate.Constants {
		e.vars[i].SetBigInt(constVal)
	}
	return e
}

// pushInput adds an input to the evaluator's input buffer.
// Inputs must be added in order, and the number of inputs must match the gate's NbInputs.
func (e *gateEvaluator) pushInput(input small_rational.SmallRational) {
	e.vars = append(e.vars, input)
}

// evaluate adds top to the top of the stack, executes the gate on it and returns the result.
// The stack is automatically reset after evaluation,
// making the evaluator ready for the next evaluation.
// NB! The result is short-lived. It will be overwritten the next time evaluate is called.
func (e *gateEvaluator) evaluate(top ...small_rational.SmallRational) *small_rational.SmallRational {
	e.vars = append(e.vars, top...)

	if len(e.vars) != e.nbIn+e.gate.NbConstants() {
		panic(fmt.Sprintf("expected a stack size of %d representing %d constants and %d inputs, got %d", e.nbIn+e.gate.NbConstants(), e.gate.NbConstants(), e.nbIn, len(e.vars)))
	}

	// Execute instructions, appending results to stack
	// The stack grows to: [constants | inputs | results]
	for i := range e.gate.Instructions {
		inst := &e.gate.Instructions[i]
		// Grow len by 1 within the pre-allocated capacity
		e.vars = e.vars[:len(e.vars)+1]
		dst := &e.vars[len(e.vars)-1]

		// Use switch instead of function pointer for better inlining
		switch inst.Op {
		case gkrcore.OpAdd:
			dst.Add(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			for j := 2; j < len(inst.Inputs); j++ {
				dst.Add(dst, &e.vars[inst.Inputs[j]])
			}
		case gkrcore.OpMul:
			dst.Mul(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			for j := 2; j < len(inst.Inputs); j++ {
				dst.Mul(dst, &e.vars[inst.Inputs[j]])
			}
		case gkrcore.OpSub:
			dst.Sub(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			for j := 2; j < len(inst.Inputs); j++ {
				dst.Sub(dst, &e.vars[inst.Inputs[j]])
			}
		case gkrcore.OpNeg:
			dst.Neg(&e.vars[inst.Inputs[0]])
		case gkrcore.OpMulAcc:
			var prod small_rational.SmallRational
			prod.Mul(&e.vars[inst.Inputs[1]], &e.vars[inst.Inputs[2]])
			dst.Add(&e.vars[inst.Inputs[0]], &prod)
		case gkrcore.OpSumExp17:
			// result = (x[0] + x[1] + x[2])^17
			var sum small_rational.SmallRational
			sum.Add(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			sum.Add(&sum, &e.vars[inst.Inputs[2]])
			dst.Mul(&sum, &sum) // x²
			dst.Mul(dst, dst)   // x⁴
			dst.Mul(dst, dst)   // x⁸
			dst.Mul(dst, dst)   // x¹⁶
			dst.Mul(dst, &sum)  // x¹⁷
		default:
			panic(fmt.Sprintf("unknown operation: %d", inst.Op))
		}
	}

	res := &e.vars[len(e.vars)-1]

	// Reset for next evaluation
	e.vars = e.vars[:e.gate.NbConstants()]

	return res
}

// gateEvaluatorPool manages a pool of gate evaluators for a specific gate type.
// All evaluators share the same underlying polynomial.Pool for element slices.
type gateEvaluatorPool struct {
	gate        gkrcore.GateBytecode
	nbIn        int
	lock        sync.Mutex
	available   []*gateEvaluator
	elementPool *polynomial.Pool
}

func newGateEvaluatorPool(gate gkrcore.GateBytecode, nbIn int, elementPool *polynomial.Pool) *gateEvaluatorPool {
	return &gateEvaluatorPool{
		gate:        gate,
		nbIn:        nbIn,
		elementPool: elementPool,
	}
}

func (gep *gateEvaluatorPool) get() *gateEvaluator {
	gep.lock.Lock()
	if n := len(gep.available); n > 0 {
		e := gep.available[n-1]
		gep.available = gep.available[:n-1]
		gep.lock.Unlock()
		return e
	}
	gep.lock.Unlock()

	e := newGateEvaluator(gep.gate, gep.nbIn, gep.elementPool)
	return &e
}

func (gep *gateEvaluatorPool) put(e *gateEvaluator) {
	gep.lock.Lock()
	gep.available = append(gep.available, e)
	gep.lock.Unlock()
}

// dumpAll dumps all available evaluator vars slices back to the polynomial pool. It is not to be used after that.
// NB! User must ensure all evaluators have been put back in the pool to prevent memory leaks.
func (gep *gateEvaluatorPool) dumpAll() {
	gep.lock.Lock()
	defer gep.lock.Unlock()
	for _, e := range gep.available {
		gep.elementPool.Dump(e.vars)
	}
	gep.available = nil
}
