//go:build js && wasm

// Copyright 2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package bls12377

import (
	"errors"
	"fmt"
	"math/big"
	"sync"

	curve "github.com/consensys/gnark-crypto/ecc/bls12-377"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fp"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr/fft"
	"github.com/consensys/gnark/backend/accelerated/webgpu/internal/bridge"
	native "github.com/consensys/gnark/backend/groth16/bls12-377"
)

const curveKey = "bls12_377"

var client = bridge.Client{GlobalName: "gnarkGroth16WebGPU", ErrorPrefix: "webgpu groth16 " + curveKey}

// Accelerator implements native.Accelerator by running the MSMs and the
// quotient computation of the Groth16 prover on the browser WebGPU runtime.
type Accelerator struct {
	pk     *native.ProvingKey
	mu     sync.Mutex
	handle string
	bases  bridge.BasisRegistry
}

// Attach uploads the bases of pk to the GPU and attaches a WebGPU accelerator
// to pk. It is idempotent.
func Attach(pk *native.ProvingKey) (*Accelerator, error) {
	if acc, ok := pk.Accelerator().(*Accelerator); ok && acc.pk == pk {
		return acc, nil
	}
	acc := &Accelerator{pk: pk}
	if err := acc.prepare(); err != nil {
		return nil, err
	}
	pk.SetAccelerator(acc)
	return acc, nil
}

func (a *Accelerator) prepare() error {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.handle != "" {
		return nil
	}
	if err := client.Init(curveKey); err != nil {
		return err
	}
	pk := a.pk
	g1 := map[string][]byte{}
	g2 := map[string][]byte{}
	addG1 := func(name string, s []curve.G1Affine) {
		g1[name] = bridge.Bytes(s)
		bridge.RegisterSlice(&a.bases, name, s)
	}
	addG1("A", pk.G1.A)
	addG1("B", pk.G1.B)
	addG1("K", pk.G1.K)
	addG1("Z", pk.G1.Z)
	for i := range pk.CommitmentKeys {
		addG1(fmt.Sprintf("commitmentBasis%d", i), pk.CommitmentKeys[i].Basis)
		addG1(fmt.Sprintf("commitmentBasisExpSigma%d", i), pk.CommitmentKeys[i].BasisExpSigma)
	}
	g2["B"] = bridge.Bytes(pk.G2.B)
	bridge.RegisterSlice(&a.bases, "B", pk.G2.B)

	handle, err := client.PrepareKey(curveKey, g1, g2)
	if err != nil {
		return err
	}
	a.handle = handle
	return client.PrewarmQuotientDomain(curveKey, int(pk.Domain.Cardinality))
}

// Release frees the GPU resources and detaches the accelerator from its proving key.
func (a *Accelerator) Release() error {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.pk.Accelerator() == native.Accelerator(a) {
		a.pk.SetAccelerator(nil)
	}
	if a.handle == "" {
		return nil
	}
	err := client.ReleaseKey(a.handle)
	a.handle = ""
	return err
}

// MultiExpG1 implements native.Accelerator.
func (a *Accelerator) MultiExpG1(bases []curve.G1Affine, scalars []fr.Element) (curve.G1Affine, error) {
	var res curve.G1Affine
	if len(scalars) > len(bases) {
		return res, errors.New(client.ErrorPrefix + ": more scalars than bases")
	}
	if len(scalars) == 0 {
		return res, nil
	}
	name, start, ok := bridge.ResolveSlice(&a.bases, bases[:len(scalars)])
	if !ok {
		return res, errors.New(client.ErrorPrefix + ": G1 bases are not part of the proving key")
	}
	packed, err := client.MSMG1(a.handle, name, start, scalarsRegularLE(scalars))
	if err != nil {
		return res, err
	}
	return decodeG1(packed)
}

// MultiExpG2 implements native.Accelerator.
func (a *Accelerator) MultiExpG2(bases []curve.G2Affine, scalars []fr.Element) (curve.G2Affine, error) {
	var res curve.G2Affine
	if len(scalars) > len(bases) {
		return res, errors.New(client.ErrorPrefix + ": more scalars than bases")
	}
	if len(scalars) == 0 {
		return res, nil
	}
	name, start, ok := bridge.ResolveSlice(&a.bases, bases[:len(scalars)])
	if !ok {
		return res, errors.New(client.ErrorPrefix + ": G2 bases are not part of the proving key")
	}
	packed, err := client.MSMG2(a.handle, name, start, scalarsRegularLE(scalars))
	if err != nil {
		return res, err
	}
	return decodeG2(packed)
}

// ComputeH implements native.Accelerator.
func (a *Accelerator) ComputeH(x, y, z []fr.Element, domain *fft.Domain) ([]fr.Element, error) {
	n := int(domain.Cardinality)
	if len(x) > n || len(y) > n || len(z) > n {
		return nil, errors.New(client.ErrorPrefix + ": evaluations larger than the domain")
	}
	h := make([]fr.Element, n)
	if err := client.ComputeH(curveKey, bridge.Bytes(x), bridge.Bytes(y), bridge.Bytes(z), n, bridge.Bytes(h)); err != nil {
		return nil, err
	}
	return h, nil
}

// scalarsRegularLE encodes scalars in regular (non Montgomery) little-endian
// form, as expected by the MSM kernels.
func scalarsRegularLE(scalars []fr.Element) []byte {
	out := make([]byte, len(scalars)*fr.Bytes)
	for i := range scalars {
		fr.LittleEndian.PutElement((*[fr.Bytes]byte)(out[i*fr.Bytes:(i+1)*fr.Bytes]), scalars[i])
	}
	return out
}

var fpModulusLimbs = func() (m [fp.Limbs]uint64) {
	words := new(big.Int).Set(fp.Modulus()).Bits()
	for i := range words {
		m[i] = uint64(words[i])
	}
	return
}()

// decodeFp reads a Montgomery-form little-endian base field element and checks
// that it is reduced.
func decodeFp(z *fp.Element, b []byte) error {
	copy(bridge.Bytes(z[:]), b)
	for i := fp.Limbs - 1; i >= 0; i-- {
		if z[i] < fpModulusLimbs[i] {
			return nil
		}
		if z[i] > fpModulusLimbs[i] {
			break
		}
	}
	return errors.New(client.ErrorPrefix + ": GPU returned a non reduced field element")
}

func decodeG1(b []byte) (curve.G1Affine, error) {
	var p curve.G1Affine
	if len(b) != 2*fp.Bytes {
		return p, fmt.Errorf("%s: expected %d G1 bytes, got %d", client.ErrorPrefix, 2*fp.Bytes, len(b))
	}
	if err := decodeFp(&p.X, b[:fp.Bytes]); err != nil {
		return p, err
	}
	if err := decodeFp(&p.Y, b[fp.Bytes:]); err != nil {
		return p, err
	}
	if !p.IsInfinity() && !p.IsOnCurve() {
		return p, errors.New(client.ErrorPrefix + ": GPU returned a G1 point that is not on the curve")
	}
	return p, nil
}

func decodeG2(b []byte) (curve.G2Affine, error) {
	var p curve.G2Affine
	if len(b) != 4*fp.Bytes {
		return p, fmt.Errorf("%s: expected %d G2 bytes, got %d", client.ErrorPrefix, 4*fp.Bytes, len(b))
	}
	for i, c := range []*fp.Element{&p.X.A0, &p.X.A1, &p.Y.A0, &p.Y.A1} {
		if err := decodeFp(c, b[i*fp.Bytes:(i+1)*fp.Bytes]); err != nil {
			return p, err
		}
	}
	if !p.IsInfinity() && !p.IsOnCurve() {
		return p, errors.New(client.ErrorPrefix + ": GPU returned a G2 point that is not on the curve")
	}
	return p, nil
}
