// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package gkr

import (
	"fmt"
	"hash"
	"math/big"

	"github.com/consensys/gnark-crypto/field/koalabear/extensions"
	"github.com/consensys/gnark-crypto/field/koalabear/extensions/polynomial"
	"github.com/consensys/gnark/internal/gkr/gkrtesting"
)

func toElement(i int64) *extensions.E6 {
	var res extensions.E6
	res.SetInt64(i)
	return &res
}

// hashFromDescription returns the hash a test vector names. The only type is "const": a
// messageCounter with step 0, so every challenge equals the given value regardless of what was
// bound to the transcript. Test vectors therefore pin down the GKR and sumcheck arithmetic only.
// Transcript handling is exercised by the tests using newMessageCounter with a nonzero step, and
// end to end by the std/gkrapi tests, which use real hashes.
func hashFromDescription(d gkrtesting.HashDescription) (hash.Hash, error) {
	if _type, ok := d["type"]; ok {
		switch _type {
		case "const":
			startState := int64(d["val"].(float64))
			return &messageCounter{startState: startState, step: 0, state: startState}, nil
		default:
			return nil, fmt.Errorf("unknown fake hash type \"%s\"", _type)
		}
	}
	return nil, fmt.Errorf("hash description missing type")
}

// messageCounterBlockSize is the length of an element's Marshal().
const messageCounterBlockSize = extensions.BytesE6

// messageCounter is a stand-in hash whose state depends only on the number of field-element
// blocks written to it, not on their values.
type messageCounter struct {
	startState int64
	state      int64
	step       int64
}

func (m *messageCounter) Write(p []byte) (n int, err error) {
	inputBlockSize := (len(p)-1)/messageCounterBlockSize + 1
	m.state += int64(inputBlockSize) * m.step
	return len(p), nil
}

func (m *messageCounter) Sum(b []byte) []byte {
	inputBlockSize := (len(b)-1)/messageCounterBlockSize + 1
	resI := m.state + int64(inputBlockSize)*m.step
	var res extensions.E6
	res.SetInt64(int64(resI))
	return (&res).Marshal()
}

func (m *messageCounter) Reset() {
	m.state = m.startState
}

func (m *messageCounter) Size() int {
	return messageCounterBlockSize
}

func (m *messageCounter) BlockSize() int {
	return messageCounterBlockSize
}

func newMessageCounter(startState, step int) hash.Hash {
	transcript := &messageCounter{startState: int64(startState), state: int64(startState), step: int64(step)}
	return transcript
}

func newMessageCounterGenerator(startState, step int) func() hash.Hash {
	return func() hash.Hash {
		return newMessageCounter(startState, step)
	}
}

// setElement parses value — a decimal or "num/den" string, or a JSON number — into a big.Rat,
// then sets z to its numerator divided by its denominator, via SetBigInt, Inverse and Mul.
func setElement(z *extensions.E6, value interface{}) (*extensions.E6, error) {
	var r big.Rat
	switch v := value.(type) {
	case string:
		if _, ok := r.SetString(v); !ok {
			return nil, fmt.Errorf("cannot parse %q", v)
		}
	case float64:
		asInt := int64(v)
		if float64(asInt) != v {
			return nil, fmt.Errorf("cannot currently parse float")
		}
		r.SetFloat64(v)
	default:
		return nil, fmt.Errorf("cannot parse value of type %T", value)
	}

	var denom extensions.E6
	z.SetBigInt(r.Num())
	denom.SetBigInt(r.Denom())
	denom.Inverse(&denom)
	z.Mul(z, &denom)
	return z, nil
}

func sliceToElementSlice[T any](slice []T) ([]extensions.E6, error) {
	elementSlice := make([]extensions.E6, len(slice))
	for i, v := range slice {
		if _, err := setElement(&elementSlice[i], v); err != nil {
			return nil, err
		}
	}
	return elementSlice, nil
}

func sliceEquals(a []extensions.E6, b []extensions.E6) error {
	if len(a) != len(b) {
		return fmt.Errorf("length mismatch %d≠%d", len(a), len(b))
	}
	for i := range a {
		if !a[i].Equal(&b[i]) {
			return fmt.Errorf("at index %d: %s ≠ %s", i, a[i].String(), b[i].String())
		}
	}
	return nil
}

func polynomialSliceEquals(a []polynomial.PolynomialE6, b []polynomial.PolynomialE6) error {
	if len(a) != len(b) {
		return fmt.Errorf("length mismatch %d≠%d", len(a), len(b))
	}
	for i := range a {
		if err := sliceEquals(a[i], b[i]); err != nil {
			return fmt.Errorf("at index %d: %w", i, err)
		}
	}
	return nil
}
