// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package gkrbn254

import (
	"errors"
	"fmt"
	"hash"
	"iter"

	"github.com/consensys/gnark-crypto/ecc/bn254/fr"
	"github.com/consensys/gnark-crypto/ecc/bn254/fr/polynomial"
	"github.com/consensys/gnark-crypto/utils"
	"github.com/consensys/gnark/constraint"
	"github.com/consensys/gnark/gkr"
	evaluator "github.com/consensys/gnark/internal/gkr/bn254"
	"github.com/consensys/gnark/internal/gkr/gkrcore"
)

// Circuit is a circuit as compiled by gkrapi.API.Compile.
type Circuit = gkrcore.SerializableCircuit

// WireAssignment is the assignment of values to the same wire across many instances of the
// circuit: WireAssignment[wireI][instanceI] is the value of wire wireI at instance instanceI. The
// values are fr.Element elements.
type WireAssignment []polynomial.MultiLin

// Proof is a GKR proof: one sumcheck proof per level of the proving schedule, followed by the
// output level's entry.
type Proof []sumcheckProof

// EvaluationClaim is an assertion that a wire's multilinear extension evaluates to Evaluation at
// EvaluationPoint.
type EvaluationClaim = gkr.EvaluationClaim[fr.Element]

// Claims are the evaluation claims on circuit inputs and outputs that Prove and Verify return, by
// wire. The consumption order within a wire's slice is up to the caller.
type Claims map[int][]EvaluationClaim

// Check asserts that every claim in c holds against assignment.
func (c Claims) Check(assignment WireAssignment) error {
	if len(c[0]) == 0 { // wire 0 is always an input, so it must have a claim
		return errors.New("no claims on wire 0")
	}
	nbVars := len(c[0][0].EvaluationPoint)
	nbInstances := 1 << nbVars
	for wI, wireClaims := range c {
		if wI < 0 || wI >= len(assignment) || len(assignment[wI]) == 0 {
			return fmt.Errorf("wire %d: no assignment", wI)
		}
		if len(assignment[wI]) != nbInstances {
			return fmt.Errorf("wire %d: %d instances, expected %d", wI, len(assignment[wI]), nbInstances)
		}
		for claimI, claim := range wireClaims {
			if len(claim.EvaluationPoint) != nbVars {
				return fmt.Errorf("wire %d claim %d: evaluation point has %d coordinates, expected %d = log(%d)", wI, claimI, len(claim.EvaluationPoint), nbVars, nbInstances)
			}
			eval := assignment[wI].Evaluate(claim.EvaluationPoint, nil)
			if !eval.Equal(&claim.Evaluation) {
				return fmt.Errorf("wire %d: claimed evaluation %v, computed %v", wI, &claim.Evaluation, &eval)
			}
		}
	}
	return nil
}

type resources struct {
	// outgoingEvalPoints[i][k] is the k-th outgoing evaluation point (evaluation challenge) produced at schedule level i.
	// outgoingEvalPoints[len(schedule)][0] holds the initial challenge (firstChallenge / rho).
	// SumcheckLevels produce one point (k=0). SkipLevels pass on all their evaluation points.
	outgoingEvalPoints [][][]fr.Element
	nbVars             int
	assignment         WireAssignment
	memPool            polynomial.Pool
	workers            *utils.WorkerPool
	circuit            Circuit
	schedule           constraint.GkrProvingSchedule
	transcript         *transcript
	claimValueIndices  [][]int // claimValueIndices[wI][claimI]: index of w's claimI-th claimed value in its source level's finalEvalProof
	claims             Claims
	consolidated       []bool // the wires of schedule[0], indexed by wire
}

// identityGate is the identity gate LevelCircuit and ConsolidationView use to build level 0's
// view of the circuit.
func identityGate() gkrcore.SerializableGate {
	return gkrcore.SerializableGate{Evaluate: gkrcore.IdentityBytecode(), NbIn: 1, Degree: 1}
}

// newResources builds the resources shared by Prove and Verify. It takes no assignment and
// creates no pools; Prove sets those up separately afterward, since Verify needs neither.
func newResources(c Circuit, schedule constraint.GkrProvingSchedule, nbVars int, hasher hash.Hash) resources {
	return resources{
		outgoingEvalPoints: make([][][]fr.Element, len(schedule)+1),
		nbVars:             nbVars,
		circuit:            c,
		schedule:           schedule,
		transcript:         gkrcore.NewHashTranscript[fr.Element](hasher),
		claimValueIndices:  c.ClaimValueIndices(schedule),
		claims:             make(Claims),
		consolidated:       c.LevelWires(schedule[0]),
	}
}

// proveSkipLevel evaluates each unique gate input at each inherited evaluation point and records
// the outgoing evaluation points on the resources.
func (r *resources) proveSkipLevel(levelI int) sumcheckProof {
	level := r.schedule[levelI].(*constraint.GkrSkipLevel)
	outPoints := gkrcore.CollectOutgoingEvalPoints(level, levelI, r.outgoingEvalPoints)

	uniqueInputs := r.circuit.UniqueGateInputs(level)
	evals := make([]fr.Element, len(uniqueInputs)*len(outPoints))
	for uiI, inW := range uniqueInputs {
		for k, point := range outPoints {
			evals[level.FinalEvalProofIndex(uiI, k)] = r.assignment[inW].Evaluate(point, &r.memPool)
		}
	}
	return sumcheckProof{finalEvalProof: evals}
}

// verifySkipLevel verifies a SkipSumcheck level: checks that the finalEvalProof is consistent with
// the gate evaluations, and records outgoing eval points.
func (r *resources) verifySkipLevel(levelI int, proof Proof) error {
	level := r.schedule[levelI].(*constraint.GkrSkipLevel)
	gkrcore.CollectOutgoingEvalPoints(level, levelI, r.outgoingEvalPoints)

	finalEval := proof[levelI].finalEvalProof
	_, inputIndices := r.circuit.InputMapping(level)
	group := constraint.GkrClaimGroup(*level)

	for levelWireI, wI := range group.Wires {
		wire := r.circuit[wI]
		evaluator := evaluator.NewGateEvaluator(wire.Gate.Evaluate, len(wire.Inputs))
		for claimI, src := range group.ClaimSources {
			for _, inI := range inputIndices[levelWireI] {
				evaluator.PushInput(finalEval[level.FinalEvalProofIndex(inI, claimI)])
			}
			gateEval := evaluator.Evaluate()
			claimedEval := proof[src.Level].finalEvalProof[r.claimValueIndices[wI][claimI]]
			if !claimedEval.Equal(gateEval) {
				return fmt.Errorf("level %d wire %d claim %d: claimed eval %v disagrees with gate eval %v", levelI, wI, claimI, &claimedEval, gateEval)
			}
		}
	}
	return nil
}

// levelPredicates returns the bind and include predicates for level levelI's unique gate inputs.
// Level 0 binds nothing and returns every one of its wires (self-referencing on the consolidation
// view); every other level binds every unique gate input that is not an unconsolidated circuit
// input, and returns claims for exactly those it withholds from binding.
func (r *resources) levelPredicates(levelI int) (bind, include func(wI int) bool) {
	if levelI == 0 {
		return func(int) bool { return false }, func(int) bool { return true }
	}
	return func(wI int) bool { return !r.circuit.IsInput(wI) || r.consolidated[wI] },
		func(wI int) bool { return r.circuit.IsInput(wI) && !r.consolidated[wI] }
}

// proveLevel proves level levelI: computes its proof entry, binds its values, and appends its claims.
func (r *resources) proveLevel(levelI int) sumcheckProof {
	var entry sumcheckProof
	switch r.schedule[levelI].(type) {
	case *constraint.GkrSkipLevel:
		entry = r.proveSkipLevel(levelI)
	case *constraint.GkrSingleSourceZeroCheckLevel:
		entry = r.proveSingleSourceZeroCheckLevel(levelI)
	case *constraint.GkrSumcheckLevel:
		entry = r.proveSumcheckLevel(levelI)
	default:
		panic(fmt.Sprintf("level %d: unknown proving level type %T", levelI, r.schedule[levelI]))
	}
	bind, include := r.levelPredicates(levelI)
	constraint.BindGkrFinalEvalProof(r.transcript, entry.finalEvalProof, r.circuit.UniqueGateInputs(r.schedule[levelI]), bind, r.schedule[levelI])
	gkrcore.AppendLevelClaims(r.claims, r.circuit, r.schedule[levelI], entry.finalEvalProof, r.outgoingEvalPoints[levelI], include)
	return entry
}

// Prove consistency of the claimed assignment. It returns the evaluation claims on the circuit's
// inputs and outputs; the caller must check them. The claim values returned to the caller, the
// output evaluations among them, are not bound into the transcript. hasher must be seeded as
// Verify requires.
func Prove(c Circuit, schedule constraint.GkrProvingSchedule, assignment WireAssignment, hasher hash.Hash) (Proof, Claims, error) {
	nbInstances := assignment.NumInstances()
	nbVars := assignment.NumVars()
	if nbVars == 0 {
		return nil, nil, errors.New("number of variables must be positive")
	}
	if 1<<nbVars != nbInstances {
		return nil, nil, errors.New("number of instances must be power of 2")
	}

	r := newResources(c, schedule, nbVars, hasher)
	r.assignment = assignment
	r.memPool = polynomial.NewPool(gkrcore.MemoryRequirements(c, nbInstances)...)
	r.workers = utils.NewWorkerPool()
	defer r.workers.Stop()

	for wireI := range c {
		if len(assignment[wireI]) == 0 {
			const minBlockSize = 64
			assignment[wireI] = make([]fr.Element, nbInstances)
			r.workers.Submit(nbInstances, func(start, end int) {
				gateEval := evaluator.NewGateEvaluator(c[wireI].Gate.Evaluate, len(c[wireI].Inputs), &r.memPool)
				for instanceI := start; instanceI < end; instanceI++ {
					for _, inputWireI := range c[wireI].Inputs {
						gateEval.PushInput(assignment[inputWireI][instanceI])
					}
					assignment[wireI][instanceI] = *gateEval.Evaluate()
				}
				gateEval.Dump()
			}, minBlockSize).Wait()
		}
	}

	proof := make(Proof, len(schedule)+1)

	// Derive the initial challenge point
	firstChallenge := make([]fr.Element, r.nbVars)
	for j := range r.nbVars {
		firstChallenge[j] = r.transcript.Challenge()
	}
	r.outgoingEvalPoints[len(schedule)] = [][]fr.Element{firstChallenge}

	outputs := c.Outputs()
	outputEvals := make([]fr.Element, len(outputs))
	for i, w := range outputs {
		outputEvals[i] = r.assignment[w].Evaluate(firstChallenge, &r.memPool)
	}
	proof[len(schedule)] = sumcheckProof{finalEvalProof: outputEvals}
	var boundOutputEvals []fr.Element
	for i, w := range outputs {
		if r.consolidated[w] {
			boundOutputEvals = append(boundOutputEvals, outputEvals[i])
		}
	}
	r.transcript.Bind(boundOutputEvals...)
	gkrcore.AppendOutputClaims(r.claims, c, firstChallenge, outputEvals, func(wI int) bool { return !r.consolidated[wI] })

	for levelI := len(schedule) - 1; levelI >= 1; levelI-- {
		proof[levelI] = r.proveLevel(levelI)
	}
	r.circuit = r.circuit.LevelCircuit(r.schedule, 0, identityGate())
	proof[0] = r.proveLevel(0)

	return proof, r.claims, nil
}

// verifyLevel verifies level levelI: checks its proof entry, binds its values, and appends its claims.
func (r *resources) verifyLevel(levelI int, proof Proof) error {
	var err error
	switch r.schedule[levelI].(type) {
	case *constraint.GkrSkipLevel:
		err = r.verifySkipLevel(levelI, proof)
	case *constraint.GkrSingleSourceZeroCheckLevel:
		err = r.verifySingleSourceZeroCheckLevel(levelI, proof)
	case *constraint.GkrSumcheckLevel:
		err = r.verifySumcheckLevel(levelI, proof)
	default:
		panic(fmt.Sprintf("level %d: unknown proving level type %T", levelI, r.schedule[levelI]))
	}
	if err != nil {
		return fmt.Errorf("level %d: %v", levelI, err)
	}
	bind, include := r.levelPredicates(levelI)
	constraint.BindGkrFinalEvalProof(r.transcript, proof[levelI].finalEvalProof, r.circuit.UniqueGateInputs(r.schedule[levelI]), bind, r.schedule[levelI])
	gkrcore.AppendLevelClaims(r.claims, r.circuit, r.schedule[levelI], proof[levelI].finalEvalProof, r.outgoingEvalPoints[levelI], include)
	return nil
}

// Verify the consistency of the claimed output with the claimed input, and return the evaluation
// claims on the circuit's inputs and outputs. A nil error means nothing until the returned Claims
// are checked: Verify reads no assignment, so the caller must call Claims.Check itself, on every
// claim, including those on exported inputs under gkrapi.ConsolidateNone, which no level
// cross-checks. The claim values returned to the caller, the output evaluations among them, are
// not bound into the transcript.
//
// The transcript starts empty, so for soundness the verifier must seed hasher, as the prover did,
// with a commitment to the circuit, the schedule, the number of instances and the input and output
// columns, computed from values it trusts.
func Verify(c Circuit, schedule constraint.GkrProvingSchedule, logNbInstances int, proof Proof, hasher hash.Hash) (Claims, error) {
	if logNbInstances == 0 {
		return nil, errors.New("number of variables must be positive")
	}
	r := newResources(c, schedule, logNbInstances, hasher)

	if len(proof) != len(schedule)+1 {
		return nil, fmt.Errorf("proof has %d levels, expected %d", len(proof), len(schedule)+1)
	}
	outputLevel := proof[len(schedule)]
	if len(outputLevel.partialSumPolys) != 0 {
		return nil, errors.New("output level has partial sum polynomials")
	}
	if len(outputLevel.finalEvalProof) != len(c.Outputs()) {
		return nil, fmt.Errorf("output level has %d evaluations, expected %d", len(outputLevel.finalEvalProof), len(c.Outputs()))
	}

	view := c.LevelCircuit(schedule, 0, identityGate())
	for levelI, level := range schedule {
		levelCircuit := c
		if levelI == 0 {
			levelCircuit = view
		}
		nbUniqueInputs := len(levelCircuit.UniqueGateInputs(level))
		wantFinalEvalLen := nbUniqueInputs * level.NbOutgoingEvalPoints()
		if len(proof[levelI].finalEvalProof) != wantFinalEvalLen {
			return nil, fmt.Errorf("level %d: got %d final evaluations, expected %d", levelI, len(proof[levelI].finalEvalProof), wantFinalEvalLen)
		}
		if _, isSkip := level.(*constraint.GkrSkipLevel); isSkip {
			if len(proof[levelI].partialSumPolys) != 0 {
				return nil, fmt.Errorf("level %d: skip level has partial sum polynomials", levelI)
			}
		} else if len(proof[levelI].partialSumPolys) != logNbInstances {
			return nil, fmt.Errorf("level %d: got %d partial sum polynomials, expected %d", levelI, len(proof[levelI].partialSumPolys), logNbInstances)
		}
	}

	// Derive the initial challenge point
	firstChallenge := make([]fr.Element, r.nbVars)
	for j := range r.nbVars {
		firstChallenge[j] = r.transcript.Challenge()
	}
	r.outgoingEvalPoints[len(schedule)] = [][]fr.Element{firstChallenge}
	var boundOutputEvals []fr.Element
	for i, w := range c.Outputs() {
		if r.consolidated[w] {
			boundOutputEvals = append(boundOutputEvals, outputLevel.finalEvalProof[i])
		}
	}
	r.transcript.Bind(boundOutputEvals...)
	gkrcore.AppendOutputClaims(r.claims, c, firstChallenge, outputLevel.finalEvalProof, func(wI int) bool { return !r.consolidated[wI] })

	for levelI := len(schedule) - 1; levelI >= 1; levelI-- {
		if err := r.verifyLevel(levelI, proof); err != nil {
			return nil, err
		}
	}
	r.circuit = view
	if err := r.verifyLevel(0, proof); err != nil {
		return nil, err
	}
	return r.claims, nil
}

// Complete the circuit evaluation from input values
func (a WireAssignment) Complete(circuit Circuit) WireAssignment {

	nbInstances := a.NumInstances()
	evaluators := make([]evaluator.GateEvaluator, len(circuit))

	for i := range circuit {
		if len(a[i]) != nbInstances {
			a[i] = make([]fr.Element, nbInstances)
		}
		if !circuit[i].IsInput() {
			evaluators[i] = evaluator.NewGateEvaluator(circuit[i].Gate.Evaluate, len(circuit[i].Inputs))
		}
	}

	for i := range nbInstances {
		for wI := range circuit {
			if !circuit[wI].IsInput() {
				for _, in := range circuit[wI].Inputs {
					evaluators[wI].PushInput(a[in][i])
				}
				a[wI][i].Set(evaluators[wI].Evaluate())
			}
		}
	}

	return a
}

// NumInstances returns the number of instances a assigns values to. It panics if a is empty.
func (a WireAssignment) NumInstances() int {
	for _, aW := range a {
		if aW != nil {
			return len(aW)
		}
	}
	panic("empty assignment")
}

// NumVars returns log₂ of the number of instances a assigns values to. It panics if a is empty.
func (a WireAssignment) NumVars() int {
	for _, aW := range a {
		if aW != nil {
			return aW.NumVars()
		}
	}
	panic("empty assignment")
}

func iterateElems(elems []fr.Element, counter *int, yield func(int, *fr.Element) bool) bool {
	for i := range elems {
		if !yield(*counter, &elems[i]) {
			return false
		}
		*counter++
	}
	return true
}

// Flatten yields the proof's elements by position. For each entry of the proof, in order, it
// yields the coefficients of its partial sum polynomials, then its final evaluations.
// DeserializeProof reads the same order.
func (p Proof) Flatten() iter.Seq2[int, *fr.Element] {
	return func(yield func(int, *fr.Element) bool) {
		var counter int
		for i := range p {
			for _, poly := range p[i].partialSumPolys {
				if !iterateElems(poly, &counter, yield) {
					return
				}
			}
			if !iterateElems(p[i].finalEvalProof, &counter, yield) {
				return
			}
		}
	}
}

// DeserializeProof is the inverse of Proof.Flatten: it rebuilds the proof for c and schedule from
// its elements. The result aliases serialized. It returns an error if the length of serialized
// does not match c and schedule.
func DeserializeProof(c Circuit, schedule constraint.GkrProvingSchedule, serialized []fr.Element) (Proof, error) {
	identity := identityGate()
	logNbInstances, err := gkrcore.ComputeLogNbInstances(c, schedule, len(serialized), identity)
	if err != nil {
		return nil, err
	}

	next := func(n int) []fr.Element {
		res := serialized[:n]
		serialized = serialized[n:]
		return res
	}

	proof := make(Proof, len(schedule)+1)
	for levelI, level := range schedule {
		levelCircuit := c.LevelCircuit(schedule, levelI, identity)
		nbUniqueInputs := len(levelCircuit.UniqueGateInputs(level))
		if _, isSkip := level.(*constraint.GkrSkipLevel); isSkip {
			proof[levelI].finalEvalProof = next(nbUniqueInputs * level.NbOutgoingEvalPoints())
		} else {
			degree := levelCircuit.ZeroCheckDegree(level)
			proof[levelI].partialSumPolys = make([]polynomial.Polynomial, logNbInstances)
			for j := range proof[levelI].partialSumPolys {
				proof[levelI].partialSumPolys[j] = next(degree)
			}
			proof[levelI].finalEvalProof = next(nbUniqueInputs)
		}
	}
	proof[len(schedule)].finalEvalProof = next(len(c.Outputs()))
	return proof, nil
}
