// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package gkr

import (
	"fmt"
	"sync"

	"github.com/consensys/gnark-crypto/ecc/bw6-761/fr"
	"github.com/consensys/gnark-crypto/ecc/bw6-761/fr/polynomial"
	"github.com/consensys/gnark/internal/gkr/gkrcore"
)

// GateEvaluator provides a high-level API for evaluating compiled gates efficiently.
// It manages the stack internally and handles input buffering, making it easy to
// evaluate the same gate multiple times with different inputs.
type GateEvaluator struct {
	gate gkrcore.GateBytecode
	vars []fr.Element
	nbIn int              // number of inputs expected
	pool *polynomial.Pool // pool vars was allocated from, if any
}

// NewGateEvaluator creates an evaluator for the given compiled gate.
// The stack is preloaded with constants and ready for evaluation.
func NewGateEvaluator(gate gkrcore.GateBytecode, nbIn int, elementPool ...*polynomial.Pool) GateEvaluator {
	e := GateEvaluator{
		gate: gate,
		nbIn: nbIn,
	}
	if len(elementPool) > 0 {
		e.pool = elementPool[0]
		e.vars = e.pool.Make(gate.EvaluatorSize(nbIn))
	} else {
		e.vars = make([]fr.Element, gate.EvaluatorSize(nbIn))
	}
	e.vars = e.vars[:gate.NbConstants()]
	for i, constVal := range gate.Constants {
		e.vars[i].SetBigInt(constVal)
	}
	return e
}

// Dump returns the evaluator's memory to the pool it was allocated from, if any, and does
// nothing otherwise. The evaluator must not be used after this.
func (e *GateEvaluator) Dump() {
	if e.pool != nil {
		e.pool.Dump(e.vars)
	}
}

// PushInput adds an input to the evaluator's input buffer.
// Inputs must be added in order, and the number of inputs must match the gate's NbInputs.
func (e *GateEvaluator) PushInput(input fr.Element) {
	e.vars = append(e.vars, input)
}

// Evaluate adds top to the top of the stack, executes the gate on it and returns the result.
// The stack is automatically reset after evaluation,
// making the evaluator ready for the next evaluation.
// NB! The result is short-lived. It will be overwritten the next time Evaluate is called.
func (e *GateEvaluator) Evaluate(top ...fr.Element) *fr.Element {
	e.vars = append(e.vars, top...)

	if len(e.vars) != e.nbIn+e.gate.NbConstants() {
		panic(fmt.Sprintf("expected a stack size of %d representing %d constants and %d inputs, got %d", e.nbIn+e.gate.NbConstants(), e.gate.NbConstants(), e.nbIn, len(e.vars)))
	}

	// Execute instructions, appending results to stack
	// The stack grows to: [constants | inputs | results]
	for i := range e.gate.Instructions {
		inst := &e.gate.Instructions[i]
		// Grow len by 1 within the pre-allocated capacity
		e.vars = e.vars[:len(e.vars)+1]
		dst := &e.vars[len(e.vars)-1]

		// Use switch instead of function pointer for better inlining
		switch inst.Op {
		case gkrcore.OpAdd:
			dst.Add(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			for j := 2; j < len(inst.Inputs); j++ {
				dst.Add(dst, &e.vars[inst.Inputs[j]])
			}
		case gkrcore.OpMul:
			dst.Mul(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			for j := 2; j < len(inst.Inputs); j++ {
				dst.Mul(dst, &e.vars[inst.Inputs[j]])
			}
		case gkrcore.OpSub:
			dst.Sub(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			for j := 2; j < len(inst.Inputs); j++ {
				dst.Sub(dst, &e.vars[inst.Inputs[j]])
			}
		case gkrcore.OpNeg:
			dst.Neg(&e.vars[inst.Inputs[0]])
		case gkrcore.OpMulAcc:
			var prod fr.Element
			prod.Mul(&e.vars[inst.Inputs[1]], &e.vars[inst.Inputs[2]])
			dst.Add(&e.vars[inst.Inputs[0]], &prod)
		case gkrcore.OpSumExp17:
			// result = (x[0] + x[1] + x[2])^17
			var sum fr.Element
			sum.Add(&e.vars[inst.Inputs[0]], &e.vars[inst.Inputs[1]])
			sum.Add(&sum, &e.vars[inst.Inputs[2]])
			dst.Mul(&sum, &sum) // x²
			dst.Mul(dst, dst)   // x⁴
			dst.Mul(dst, dst)   // x⁸
			dst.Mul(dst, dst)   // x¹⁶
			dst.Mul(dst, &sum)  // x¹⁷
		default:
			panic(fmt.Sprintf("unknown operation: %d", inst.Op))
		}
	}

	res := &e.vars[len(e.vars)-1]

	// Reset for next evaluation
	e.vars = e.vars[:e.gate.NbConstants()]

	return res
}

// GateEvaluatorPool manages a pool of gate evaluators for a specific gate type.
// All evaluators share the same underlying polynomial.Pool for element slices.
type GateEvaluatorPool struct {
	gate        gkrcore.GateBytecode
	nbIn        int
	lock        sync.Mutex
	available   []*GateEvaluator
	elementPool *polynomial.Pool
}

func NewGateEvaluatorPool(gate gkrcore.GateBytecode, nbIn int, elementPool *polynomial.Pool) *GateEvaluatorPool {
	return &GateEvaluatorPool{
		gate:        gate,
		nbIn:        nbIn,
		elementPool: elementPool,
	}
}

func (gep *GateEvaluatorPool) Get() *GateEvaluator {
	gep.lock.Lock()
	if n := len(gep.available); n > 0 {
		e := gep.available[n-1]
		gep.available = gep.available[:n-1]
		gep.lock.Unlock()
		return e
	}
	gep.lock.Unlock()

	e := NewGateEvaluator(gep.gate, gep.nbIn, gep.elementPool)
	return &e
}

func (gep *GateEvaluatorPool) Put(e *GateEvaluator) {
	gep.lock.Lock()
	gep.available = append(gep.available, e)
	gep.lock.Unlock()
}

// DumpAll dumps all available evaluators' memory back to the pool. It is not to be used after that.
// NB! User must ensure all evaluators have been put back in the pool to prevent memory leaks.
func (gep *GateEvaluatorPool) DumpAll() {
	gep.lock.Lock()
	defer gep.lock.Unlock()
	for _, e := range gep.available {
		e.Dump()
	}
	gep.available = nil
}
