// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package gkrbw6761

import (
	"fmt"
	"hash"

	"github.com/consensys/gnark-crypto/ecc/bw6-761/fr"
	"github.com/consensys/gnark/internal/gkr/gkrtesting"
)

// hashFromDescription returns the hash a test vector names. The only type is "const": a
// messageCounter with step 0, so every challenge equals the given value regardless of what was
// absorbed by the transcript. Test vectors therefore pin down the GKR and sumcheck arithmetic only.
// Transcript handling is exercised by the tests using newMessageCounter with a nonzero step, and
// end to end by the std/gkrapi tests, which use real hashes.
func hashFromDescription(d gkrtesting.HashDescription) (hash.Hash, error) {
	if _type, ok := d["type"]; ok {
		switch _type {
		case "const":
			startState := int64(d["val"].(float64))
			return &messageCounter{startState: startState, step: 0, state: startState}, nil
		default:
			return nil, fmt.Errorf("unknown fake hash type \"%s\"", _type)
		}
	}
	return nil, fmt.Errorf("hash description missing type")
}

// messageCounterBlockSize is the length of an element's Marshal().
const messageCounterBlockSize = fr.Bytes

// messageCounter is a stand-in hash whose state depends only on the number of field-element
// blocks written to it, not on their values.
type messageCounter struct {
	startState int64
	state      int64
	step       int64
}

func (m *messageCounter) Write(p []byte) (n int, err error) {
	inputBlockSize := (len(p)-1)/messageCounterBlockSize + 1
	m.state += int64(inputBlockSize) * m.step
	return len(p), nil
}

func (m *messageCounter) Sum(b []byte) []byte {
	inputBlockSize := (len(b)-1)/messageCounterBlockSize + 1
	resI := m.state + int64(inputBlockSize)*m.step
	var res fr.Element
	res.SetInt64(int64(resI))
	return (&res).Marshal()
}

func (m *messageCounter) Reset() {
	m.state = m.startState
}

func (m *messageCounter) Size() int {
	return messageCounterBlockSize
}

func (m *messageCounter) BlockSize() int {
	return messageCounterBlockSize
}

func newMessageCounter(startState, step int) hash.Hash {
	transcript := &messageCounter{startState: int64(startState), state: int64(startState), step: int64(step)}
	return transcript
}

func newMessageCounterGenerator(startState, step int) func() hash.Hash {
	return func() hash.Hash {
		return newMessageCounter(startState, step)
	}
}
